main:
- name: Research
  url: /#research
  weight: 10
- name: Projects
  url: /#projects
  weight: 20
- name: About
  url: /#about
  weight: 30
- name: Problem solving
  url: /#problem-solving
  weight: 35
- name: CV ↗
  url: uploads/resume.pdf
  weight: 40
