main:
- name: Research
  url: /#research
  weight: 10
- name: Projects
  url: /#projects
  weight: 20
- name: Skills
  url: /#skills
  weight: 25
- name: About
  url: /#about
  weight: 30
- name: CV ↗
  url: uploads/resume.pdf
  weight: 40
